spring:
  datasource:
    url: "jdbc:postgresql://ec2-44-209-24-62.compute-1.amazonaws.com:5432/dnltbrl88t21b"
    username: iwszbcmeuuybja
    password: 77b1cce0d9f4f0ecbb402ee67ddd7dbd956da1e5c7a5e865f312b299127b2503
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        "[globally_quoted_identifiers]": true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  mail: 
    host: smtp.gmail.com
    port: 587
    username: kidsdrawing.company@gmail.com
    password: wtvjqavetpafomcb
    properties:
      mail: 
        smtp:
          auth: true
          starttls:
            enable: true
jwt_secret: 8d0430fbb7e52620bca66c47cb80c1a9b844e629195010f4c27643528ea021838812c9f6669f979fe7431ea210014737ca08a05e568d82eefecaab5624d163b9
app.firebase-configuration-file: messaging-fcm-bc512-firebase-adminsdk-p231d-c6cb2a0c93.json