spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: postgres
    password: 123
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        "[globally_quoted_identifiers]": true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  mail: 
    host: smtp.gmail.com
    port: 587
    username: kidsdrawing.company@gmail.com
    password: wtvjqavetpafomcb
    properties:
      mail: 
        smtp:
          auth: true
          starttls:
            enable: true
jwt_secret: 8d0430fbb7e52620bca66c47cb80c1a9b844e629195010f4c27643528ea021838812c9f6669f979fe7431ea210014737ca08a05e568d82eefecaab5624d163b9
app.firebase-configuration-file: messaging-fcm-bc512-firebase-adminsdk-p231d-c6cb2a0c93.json