### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE classes ACTION ###
# @name create_classes

POST {{rest}}/classes
Content-Type: application/json

{
    "name": "Lớp mầm chì màu 4 đến 6 tuổi 1",
    "creator_id": 3,
    "user_register_teach_semester": 1,
    "security_code": "CM-1HK2022"
}

### 
# @name update_classes

PUT {{rest}}/classes/3
Content-Type: application/json

{
    "name": "Cuộc thi vẽ tranh gia đình",
    "description": "Vẽ về những người thân trong gia đình",
    "max_participant": 50,
    "registration_time": "2022-07-12T12:59:11.332",
    "image_url": "https://res.cloudinary.com/djtmwajiu/image/upload/v1656344895/tranh-bao-ve-moi-truong-01_gpsyin.png",
    "start_time": "2022-08-12T12:59:11.332",
    "end_time": "2022-09-12T12:59:11.332",
    "is_enabled": true,
    "creator_id": 3,
    "art_age_id": 1,
    "art_type_id": 1
}

### GET classes ACTION ###
# @name get_classes

GET  {{rest}}/classes



### GET classes ACTION ###
# @name get_classes

GET  {{rest}}/classes/info/2

### GET classes ACTION ###
# @name get_classes

GET  {{rest}}/classes/student/22

### GET classes ACTION ###
# @name get_classes

GET  {{rest}}/classes/student/detail/18


### GET classes ACTION ###
# @name get_classes

GET  {{rest}}/classes/schedule-all

### GET classes ACTION ###
# @name get_classes

GET  {{rest}}/classes/schedule-child/18

### GET classes ACTION ###
# @name get_classes

GET  {{rest}}/classes/schedule-allchild/12

### GET classes ACTION ###
# @name get_classes

GET  {{rest}}/classes/parent/12

### GET classes ACTION ###
# @name get_classes

GET  {{rest}}/classes/student/22

### GET classes ACTION ###
# @name get_classes

GET  {{rest}}/classes/teacher-list/2

### GET classes ACTION ###
# @name get_classes

GET  {{rest}}/classes/class-parent/childs/7/12

### GET classes ACTION ###
# @name get_classes

GET  {{rest}}/classes/teacher-1/2