### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/contest
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "name": "Cuộc thi vẽ tranh đề tài mỗi trường",
    "description": "Vẽ về những thứ xung quanh chúng ta",
    "max_participant": 100,
    "registration_time": "2022-07-12T12:59:11.332",
    "image_url": "https://res.cloudinary.com/djtmwajiu/image/upload/v1660037600/mmjhxh9dun1secngcljk.png",
    "start_time": "2022-07-12T12:59:11.332",
    "end_time": "2022-08-12T12:59:11.332",
    "is_enabled": true,
    "creator_id": 1,
    "art_age_id": 2,
    "art_type_id": 1
}

### 
# @name update_contest

PUT {{rest}}/contest/3
Content-Type: application/json

{
    "name": "Cuộc thi vẽ tranh gia đình",
    "description": "Vẽ về những người thân trong gia đình",
    "max_participant": 50,
    "registration_time": "2022-07-12T12:59:11.332",
    "image_url": "https://res.cloudinary.com/djtmwajiu/image/upload/v1656344895/tranh-bao-ve-moi-truong-01_gpsyin.png",
    "start_time": "2022-08-12T12:59:11.332",
    "end_time": "2022-09-12T12:59:11.332",
    "is_enabled": true,
    "creator_id": 3,
    "art_age_id": 1,
    "art_type_id": 1
}

### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/contest

### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/contest/student/18

### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/contest/parent/8

### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/contest/24818b8c-a1d7-4fdf-9b86-a4847f137010