### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE COURSE ACTION ###
# @name create_course

POST {{rest}}/course/v2
Content-Type: application/json
Authorization: Bearer {{admin_access_token}}

{
    "name": "Khóa học sơn dầu cơ bản",
    "description": "test",
    "num_of_section": 10,
    "price": 2000000,
    "image_url": "",
    "is_enabled": false,
    "creator_id": 1,
    "art_age_id": 1,
    "art_type_id": 2,
    "art_level_id": 1
}

### 
# @name update_contest

PUT {{rest}}/course/3
Content-Type: application/json

{
    "name": "Khóa học mầm sơn dầu cơ bản",
    "description": "<p>hello nguyen van chung</p>",
    "max_participant": 20,
    "num_of_section": 10,
    "price": 2000000,
    "image_url": "",
    "is_enabled": false,
    "creator_id": 3,
    "art_age_id": 1,
    "art_type_id": 2,
    "art_level_id": 1
}

### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/course/id/4

### GET USER GRADE CONTEST ACTION ###
# @name get_all_user_grade_contest

GET {{rest}}/course?page=0&size=10


### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/course/report


### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/course/parent/12


### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/course/student-new/22


### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/course/parent-new/12


### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/course/teacher-new/0a687fdd-f2be-4a6b-8d21-462780408702


### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/course/teacher/new/0a687fdd-f2be-4a6b-8d21-462780408702