### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "teacher-1",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/exercises
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "section_id": 41,
    "level_id": 1,
    "name": "Bài tập 1",
    "description": "<p>Vẽ con chó<p>"
}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/exercises
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "section_id": 42,
    "level_id": 1,
    "name": "Bài tập 2",
    "description": "<p>Vẽ con mèo<p>"
}

### 
# @name update_contest

PUT {{rest}}/exercises/1
Content-Type: application/json

{
    "name": "Học kì 1 năm học 2022",
    "description": "xxx",
    "number": 1,
    "start_time": "2022-08-12T12:59:11.332",
    "year": 2022,
    "creator_id": 3
}

### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/exercises/section/66


### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/exercises/section/66