### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "teacher-1",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/exercises
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "section_id": 18,
    "level_id": 1,
    "name": "Bài tập 3",
    "description": "<p>Vẽ con nguời thân 3<p>"
}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/exercises
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "section_id": 25,
    "level_id": 3,
    "name": "Bài kiểm tra cuối kì",
    "description": "<p>Vẽ hình ngôi nhà<p>"
}

### 
# @name update_contest

PUT {{rest}}/exercises/1
Content-Type: application/json

{
    "name": "Học kì 1 năm học 2022",
    "description": "xxx",
    "number": 1,
    "start_time": "2022-08-12T12:59:11.332",
    "year": 2022,
    "creator_id": 3
}

### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/exercises/section/66


### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/exercises/section-teacher/62

### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/exercises/section/student/66


### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/exercises/class-student/7/32

### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/exercises/class-parent/7/12


### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/exercises/section-student/18/18