### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "student-3",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/exercise-submission
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "student_id": 20,
    "exercise_id": 5,
    "image_url": "https://res.cloudinary.com/djtmwajiu/image/upload/v1656344895/tranh-bao-ve-moi-truong-01_gpsyin.png"
}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/exercise-submission
Content-Type: application/json

{
    "name": "Học kì 2 năm học 2022",
    "description": "",
    "number": 2,
    "start_time": "2022-12-12T12:59:11.332",
    "year": 2022,
    "creator_id": 3
}

### 
# @name update_contest

PUT {{rest}}/exercise-submission/1
Content-Type: application/json

{
    "name": "Học kì 1 năm học 2022",
    "description": "xxx",
    "number": 1,
    "start_time": "2022-08-12T12:59:11.332",
    "year": 2022,
    "creator_id": 3
}

### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/exercise-submission/exercise/4


### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/exercise-submission/class/23


### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/exercise-submission/student/8

### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/exercise-submission/classes-student/3/20
