### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/final-course/16/5

### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/final-course/student/22