### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "student-1_1",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST {{rest}}/notification
Content-Type: application/json

{
    "fcmToken": "cuIe4nGRxVxO4fHTw1lLPy:APA91bH3_T6RrNiSMibeD35EsrZpffCqmOQ3VSSp4g9YZOUrkW8-DKP0gW1odPwzrCg2tlu3T2QrDN3bNEcPY80O69nIp1kF3XlFGJ8JXFZrHa7RNfk4CpYJIeesisNKfmR0BzPOq2rm",
    "title": "Nghỉ học",
    "body": "xxxx"
}

