@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST {{rest}}/notification
Content-Type: application/json

{
    "fcmToken": "cVVucbNk5Q6nRZ_LATNbJX:APA91bGlhak8RCEtSQjKs-HJXQcvlyk7v_fB_zLivO8Os4noms1nZyBK5RckHE47qI_04avsCRnajhSTCkbtxxi6Qy3B7T4vMZ0hOOuv4mHumoZcMpmupMHTEjLPChN7logfzmUEe9Wd",
    "title": "Nghỉ học",
    "body": "xxxx"
}

