@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE SCHEDULE CLASS ACTION ###
# @name create_schedule_class

POST {{rest}}/password-reset-token/user/resetPassword/chungnguyen10012000@gmail.com


### CREATE SCHEDULE CLASS ACTION ###
# @name create_schedule_class

GET {{rest}}/password-reset-token/user/changePassword/57b18fee-c5b0-45f8-a1f5-207416253687