### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "student-1_1",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/role
Content-Type: application/json

{
    "name": "ADMIN_USER",
    "description": "Role for admin"
}


### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/role
Content-Type: application/json

{
    "name": "TEACHER_USER",
    "description": "Role for teacher"
}



### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/role
Content-Type: application/json

{
    "name": "PARENT_USER",
    "description": "Role for parent"
}



### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/role
Content-Type: application/json

{
    "name": "STUDENT_USER",
    "description": "Role for student"
}