### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE SCHEDULE CLASS ACTION ###
# @name create_schedule_class

POST {{rest}}/semester/schedule-class/4
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "time": ["2022-10-01", "2022-11-02", "2022-10-03", "2022-10-04"]
}


### CREATE SCHEDULE CLASS ACTION ###
# @name create_schedule_class

POST {{rest}}/semester/schedule-class/1
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "time": ["2022-01-01"]
}


### CREATE SCHEDULE CLASS ACTION ###
# @name create_schedule_class

POST {{rest}}/semester/schedule-class/2
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "time": ["2022-04-02", "2022-05-05"]
}


### CREATE SCHEDULE CLASS ACTION ###
# @name create_schedule_class

POST {{rest}}/semester/schedule-class/3
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "time": ["2022-07-07", "2022-08-08"]
}


### CREATE SCHEDULE CLASS ACTION ###
# @name create_schedule_class

POST {{rest}}/semester/schedule-class/heroku/4
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "time": ["2022-10-01", "2022-11-02", "2022-10-03", "2022-10-04"]
}




### GET CLASSES INFORMATION ACTION ###
# @name get_info_classes
GET {{rest}}/classes/info/3
Authorization: Bearer {{admin_access_token}}


### GET CLASSES ACTION ###
# @name get_classes

GET  {{rest}}/classes/info