### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "student-1_1",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/section
Content-Type: application/json

{
    "classes_id": 18,
    "name": "Học kì 1 năm học 2022",
    "description": "",
    "number": 1,
    "recording": "",
    "message": ""
}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/section
Content-Type: application/json

{
    "name": "Học kì 2 năm học 2022",
    "description": "",
    "number": 2,
    "start_time": "2022-12-12T12:59:11.332",
    "year": 2022,
    "creator_id": 3
}

### 
# @name update_contest

PUT {{rest}}/section/1
Content-Type: application/json

{
    "name": "Học kì 1 năm học 2022",
    "description": "xxx",
    "number": 1,
    "start_time": "2022-08-12T12:59:11.332",
    "year": 2022,
    "creator_id": 3
}

### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/section


### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/section/class/7


### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/section/class-teacher/7


### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/section/class-student/7/22