### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "student-1_1",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/section-template
Content-Type: application/json

{
    "creator_id": 1,
    "course_id": 1,
    "name": "Giaos an 1",
    "description": "",
    "number": 1,
    "teaching_form": true
}

PUT {{rest}}/section-template/1
Content-Type: application/json

{
    "creator_id": 1,
    "course_id": 1,
    "name": "Giao an 2",
    "description": "",
    "number": 1,
    "teaching_form": true
}

### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/section-template/course/6c1db240-6bf8-4635-b04a-bb5c9a31d6b1