### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST  {{rest}}/semester-class
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "semester_id": 1,
    "course_id": 1,
    "name": "Lớp mầm chì màu 2"
}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST {{rest}}/semester-class
Content-Type: application/json

{
    "name": "Lịch học 2",
    "creator_id": 3
}

### UPDATE ART TYPE ACTION ###
# @name update_art_type

PUT {{rest}}/semester-class/8
Content-Type: application/json

{
    "name": "Lịch học 1_1",
    "creator_id": 3
}

### REMOVE ART TYPE ACTION ###
# @name update_art_type

DELETE  {{rest}}/lesson-time/2

### GET ART TYPE ACTION ###
# @name get_art_type

GET {{rest}}/semester-class/15

### GET ART TYPE ACTION ###
# @name get_all_art_type


### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/semester-class/new


### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/semester-class/student-course/18/1