### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/semester
Content-Type: application/json
Authorization: Bearer {{admin_access_token}}

{
    "name": "Học kì 1 năm học 2022",
    "description": "",
    "number": 1,
    "start_time": "2022-09-01T00:00:00",
    "end_time": "2022-11-01T00:00:00",
    "year": 2022,
    "creator_id": 1
}


### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/semester
Content-Type: application/json
Authorization: Bearer {{admin_access_token}}

{
    "name": "Học kì 2 năm học 2022",
    "description": "",
    "number": 2,
    "start_time": "2022-10-01T00:00:00",
    "end_time": "2022-12-01T00:00:00",
    "year": 2022,
    "creator_id": 1
}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/semester
Content-Type: application/json

{
    "name": "Học kì 2 năm học 2022",
    "description": "",
    "number": 2,
    "start_time": "2022-12-12T12:59:11.332",
    "year": 2022,
    "creator_id": 1
}

### 
# @name update_contest

PUT {{rest}}/semester/1
Content-Type: application/json

{
    "name": "Học kì 2 năm học 2022",
    "description": "xxx",
    "number": 1,
    "start_time": "2022-08-12T12:59:11.332",
    "year": 2022,
    "creator_id": 1
}

### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/semester