### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST  {{rest}}/semester-class
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "semester_id": 3,
    "course_id": 1,
    "name": "Lớp mầm chì màu"
}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST {{rest}}/semester-class
Content-Type: application/json

{
    "name": "Lịch học 2",
    "creator_id": 3
}

### UPDATE ART TYPE ACTION ###
# @name update_art_type

PUT {{rest}}/semester-class/8
Content-Type: application/json

{
    "name": "Lịch học 1_1",
    "creator_id": 3
}

### REMOVE ART TYPE ACTION ###
# @name update_art_type

DELETE  {{rest}}/lesson-time/2

### GET ART TYPE ACTION ###
# @name get_art_type

GET {{rest}}/semester-class/1

### GET ART TYPE ACTION ###
# @name get_all_art_type


### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/semester-class/new


### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/semester-class/student-course/22/1


### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/semester-class/teacher-course/8d751edb-7e9c-466d-a0e3-69fec1593194/6c1db240-6bf8-4635-b04a-bb5c9a31d6b1


### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/semester-class


### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/semester-class/0a7996d1-9f8a-42c9-86a1-e439e1bbaa33