@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST {{rest}}/semester-course
Content-Type: application/json

{
    "creation_id": 13,
    "course_id": 4,
    "schedule_id": 8

}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST {{rest}}/semester-course
Content-Type: application/json

{
    "name": "Lịch học 2",
    "creator_id": 3
}

### UPDATE ART TYPE ACTION ###
# @name update_art_type

PUT {{rest}}/semester-course/8
Content-Type: application/json

{
    "name": "Lịch học 1_1",
    "creator_id": 3
}

### REMOVE ART TYPE ACTION ###
# @name update_art_type

DELETE  {{rest}}/lesson-time/2

### GET ART TYPE ACTION ###
# @name get_art_type

GET {{rest}}/semester-course/15

### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/semester-course?page=0&size=2