@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/sendEmail/sendMailWithAttachment
Content-Type: application/json

{
    "recipient": "chungnguyen10012000@gmail.com",
    "msgBody": "Chào mừng bạn đến với KidsDrawing!",
    "subject": "Tài khoản KidsDrawing",
    "attachment": "https://kids-drawing-type-script.vercel.app/auth"
}