### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "student-1_1",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/sendEmail
Content-Type: application/json

{
    "recipient": "chung.nguyen10012001@hcmut.edu.vn",
    "msgBody": "Chào mừng bạn đến với KidsDrawing!",
    "subject": "Tài khoản KidsDrawing", 
}


### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/sendEmail/student
Content-Type: application/json

{
    "msgBody": "Chào mừng bạn đến với KidsDrawing!",
    "subject": "Tài khoản KidsDrawing",
    "attachment": ""
}