### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST {{rest}}/schedule
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "lesson_time": 2,
    "semester_class_id": 1,
    "date_of_week": 6
}