### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "student-1",
    "password": "123"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

POST {{rest}}/student-leave
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "section_id": 42,
    "student_id": 8,
    "classes_id": 23,
    "description": "Em bị ốm"
}

### GET student GRADE semester ACTION ###
# @name get_student_grade_semester

GET {{rest}}/student-leave/1

### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

GET {{rest}}/student-leave

### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

GET {{rest}}/student-leave/section-student/10/26


### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

GET {{rest}}/student-leave/class-student/23/8

### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

GET {{rest}}/student-leave/class-parent/2/12

### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

GET {{rest}}/student-leave/teacher/5


### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

DELETE {{rest}}/student-leave/4/21
Authorization: Bearer {{admin_access_token}}

### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

PUT {{rest}}/student-leave/admin/1
Content-Type: application/json

{
    "reviewer_id": 3,
    "status": true
}