### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "student-1",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE STUDENT REGISTER JOIN CONTEST ACTION ###
# @name create_student_register_join_contest

POST {{rest}}/user-register-join-contest
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "student_id": 30,
    "contest_id": 2
}

### GET TEACHER GRADE CONTEST ACTION ###
# @name get_teacher_grade_contest

GET {{rest}}/user-register-join-contest/3

### GET USER GRADE CONTEST ACTION ###
# @name get_all_user_grade_contest

GET {{rest}}/user-register-join-contest/student/1?page=0&size=10

### GET USER GRADE CONTEST ACTION ###
# @name get_all_user_grade_contest

GET {{rest}}/user-register-join-contest/contest-parent/1/12