@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

POST {{rest}}/student-leave
Content-Type: application/json

{
    "section_id": 1,
    "student_id": 1,
    "class_id": 18,
    "description": ""
}

### GET student GRADE semester ACTION ###
# @name get_student_grade_semester

GET {{rest}}/student-leave/1

### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

GET {{rest}}/student-leave

### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

PUT {{rest}}/student-leave/admin/1
Content-Type: application/json

{
    "reviewer_id": 3,
    "status": true
}