### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "teacher-1",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

POST {{rest}}/teacher-leave
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "section_id": 42,
    "teacher_id": 8,
    "class_id": 23,
    "substitute_teacher_id": 9,
    "description": "<p>Yêu cầu dạy thay lớp</p>"
}

### GET TEACHER GRADE semester ACTION ###
# @name get_teacher_grade_semester

GET {{rest}}/teacher-leave/1

### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

GET {{rest}}/teacher-leave


### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

GET {{rest}}/teacher-leave/teacher/2

### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

PUT {{rest}}/teacher-leave/admin/1
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "reviewer_id": 1,
    "status": "Approved"
}