@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE ART TYPE ACTION ###
# @name create_art_type

POST {{rest}}/teacher-register-level
Content-Type: application/json

{
    "teacher_id": 3,
    "art_type_id": 1,
    "art_age_id": 1,
    "degree_photo_url": "https://res.cloudinary.com/djtmwajiu/image/upload/v1656344895/tranh-bao-ve-moi-truong-01_gpsyin.png",
    "status": false
}

### CREATE ART TYPE ACTION ###
# @name create_art_type

PUT {{rest}}/teacher-register-level/2
Content-Type: application/json

{
    "teacher_id": 3,
    "art_type_id": 1,
    "art_age_id": 1,
    "degree_photo_url": "https://res.cloudinary.com/djtmwajiu/image/upload/v1656344895/vegiadinh_c48g9o.jpg",
    "status": false
}

### CREATE ART TYPE ACTION ###
# @name create_art_type

PUT {{rest}}/teacher-register-level/admin/2/2

### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/teacher-register-level/teacher/3?page=0&size=1