@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

POST {{rest}}/teacher-leave
Content-Type: application/json

{
    "section_id": 1,
    "teacher_id": 4,
    "class_id": 18,
    "substitute_teacher_id": 5,
    "description": ""
}

### GET TEACHER GRADE semester ACTION ###
# @name get_teacher_grade_semester

GET {{rest}}/teacher-leave/17

### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

GET {{rest}}/teacher-leave

### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

PUT {{rest}}/teacher-leave/admin/17
Content-Type: application/json

{
    "section_id": 1,
    "teacher_id": 4,
    "class_id": 18,
    "substitute_teacher_id": 5,
    "description": ""
}