### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "teacher-1",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

POST {{rest}}/teacher-teach-semester
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "teacher_id": 5,
    "semester_classes_id": 2
}

### GET TEACHER GRADE semester ACTION ###
# @name get_teacher_grade_semester

GET {{rest}}/teacher-teach-semester/17

### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

GET {{rest}}/teacher-teach-semester

### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

PUT {{rest}}/teacher-teach-semester/admin/17
Content-Type: application/json

{
    "reviewer_id": 3,
    "status": true
}