### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/tutorial-template-page
Content-Type: application/json
Authorization: Bearer {{admin_access_token}}

{
    "section_template_id": 11,
    "name": "Trang 1",
    "description": "<h3><strong>Phần 3: Tô màu&nbsp;&nbsp;</strong></h3><h5><strong>Bước 7:&nbsp;Kết thúc phần dựng hình, các bạn chuẩn bị dụng cụ để bắt đầu phần tô màu nhé.&nbsp;&nbsp;</strong></h5><ul><li>Chúng mình cần có cọ, màu poster, bảng pha màu, ly đựng nước và giẻ lau.&nbsp;&nbsp;</li><li>Mình tô phần vỏ bánh trước, Zest sử dụng màu nâu nhạt để tô, ngoài ra bạn còn có thể dùng màu vàng nâu, màu vàng nhạt nữa nhé</li></ul><p><img src=\"https://zestart.vn/wp-content/uploads/2021/10/Huong-dan-be-ve-tranh-chiec-banh-ma-quai-Zest-art-8.jpg\"></p>",
    "number": 1
}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/tutorial-template-page
Content-Type: application/json
Authorization: Bearer {{admin_access_token}}

{
    "name": "Học kì 2 năm học 2022",
    "description": "",
    "number": 2,
    "start_time": "2022-12-12T12:59:11.332",
    "year": 2022,
    "creator_id": 3
}

### 
# @name update_contest

PUT {{rest}}/tutorial-template-page/1
Content-Type: application/json

{
    "name": "Học kì 1 năm học 2022",
    "description": "xxx",
    "number": 1,
    "start_time": "2022-08-12T12:59:11.332",
    "year": 2022,
    "creator_id": 3
}

### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/tutorial-template-page


### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/tutorial-template-page/section-template/2