@rest = {{$dotenv HOST}}/{{$dotenv API}}


### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-100",
    "password": "12345678aA@",
    "email": "student-100@gmail.com",
    "firstName": "student",
    "lastName": "1",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 6,
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-2",
    "password": "12345678aA@",
    "email": "student-2@gmail.com",
    "firstName": "student",
    "lastName": "2",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 6,
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-3",
    "password": "12345678aA@",
    "email": "student-3@gmail.com",
    "firstName": "student",
    "lastName": "3",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 7,
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-4",
    "password": "12345678aA@",
    "email": "student-4@gmail.com",
    "firstName": "student",
    "lastName": "4",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 7,
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-5",
    "password": "12345678aA@",
    "email": "student-5@gmail.com",
    "firstName": "student",
    "lastName": "5",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 8,
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-6",
    "password": "12345678aA@",
    "email": "student-6@gmail.com",
    "firstName": "student",
    "lastName": "6",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 8,
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-7",
    "password": "a8726357",
    "email": "student-7@gmail.com",
    "firstName": "student",
    "lastName": "7",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 9,
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-8",
    "password": "12345678aA@",
    "email": "student-8@gmail.com",
    "firstName": "student",
    "lastName": "8",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 9,
    "roleNames": ["STUDENT_USER"]
}


### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-9",
    "password": "12345678aA@",
    "email": "student-9@gmail.com",
    "firstName": "student",
    "lastName": "9",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 10,
    "roleNames": ["STUDENT_USER"]
}


### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-10",
    "password": "12345678aA@",
    "email": "student-10@gmail.com",
    "firstName": "student",
    "lastName": "10",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 10,
    "roleNames": ["STUDENT_USER"]
}


### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-11",
    "password": "12345678aA@",
    "email": "student-11@gmail.com",
    "firstName": "student",
    "lastName": "11",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 6,
    "roleNames": ["STUDENT_USER"]
}


### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-12",
    "password": "12345678aA@",
    "email": "student-12@gmail.com",
    "firstName": "student",
    "lastName": "12",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 11,
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-13",
    "password": "12345678aA@",
    "email": "student-13@gmail.com",
    "firstName": "student",
    "lastName": "13",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 11,
    "roleNames": ["STUDENT_USER"]
}


### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-14",
    "password": "12345678aA@",
    "email": "student-14@gmail.com",
    "firstName": "student",
    "lastName": "14",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 12,
    "roleNames": ["STUDENT_USER"]
}



### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-15",
    "password": "12345678aA@",
    "email": "student-15@gmail.com",
    "firstName": "student",
    "lastName": "15",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 12,
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-16",
    "password": "12345678aA@",
    "email": "student-16@gmail.com",
    "firstName": "student",
    "lastName": "16",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 13,
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-17",
    "password": "12345678aA@",
    "email": "student-17@gmail.com",
    "firstName": "student",
    "lastName": "17",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 13,
    "roleNames": ["STUDENT_USER"]
}


### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-18",
    "password": "12345678aA@",
    "email": "student-18@gmail.com",
    "firstName": "student",
    "lastName": "18",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 14,
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-19",
    "password": "12345678aA@",
    "email": "student-19@gmail.com",
    "firstName": "student",
    "lastName": "19",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 14,
    "roleNames": ["STUDENT_USER"]
}


### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-20",
    "password": "12345678aA@",
    "email": "student-20@gmail.com",
    "firstName": "student",
    "lastName": "20",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 15,
    "roleNames": ["STUDENT_USER"]
}


### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-21",
    "password": "12345678aA@",
    "email": "student-21@gmail.com",
    "firstName": "student",
    "lastName": "21",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_id": 15,
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/user
Content-Type: application/json

{
    "username": "parent-1",
    "password": "a8726357",
    "email": "chungnguyen10012000@gmail.com",
    "firstName": "parent",
    "lastName": "1",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "roleNames": ["PARENT_USER"]
}

### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/user
Content-Type: application/json

{
    "username": "parent-2",
    "password": "12345678aA@",
    "email": "parent-2@gmail.com",
    "firstName": "parent",
    "lastName": "2",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "roleNames": ["PARENT_USER"]
}

### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/user
Content-Type: application/json

{
    "username": "parent-3",
    "password": "12345678aA@",
    "email": "parent-3@gmail.com",
    "firstName": "parent",
    "lastName": "3",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "roleNames": ["PARENT_USER"]
}

### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/user
Content-Type: application/json

{
    "username": "parent-4",
    "password": "12345678aA@",
    "email": "parent-4@gmail.com",
    "firstName": "parent",
    "lastName": "4",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "roleNames": ["PARENT_USER"]
}

### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/user
Content-Type: application/json

{
    "username": "parent-5",
    "password": "12345678aA@",
    "email": "parent-5@gmail.com",
    "firstName": "parent",
    "lastName": "5",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "roleNames": ["PARENT_USER"]
}


### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/user
Content-Type: application/json

{
    "username": "parent-6",
    "password": "12345678aA@",
    "email": "parent-6@gmail.com",
    "firstName": "parent",
    "lastName": "6",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "roleNames": ["PARENT_USER"]
}


### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/user
Content-Type: application/json

{
    "username": "parent-7",
    "password": "12345678aA@",
    "email": "parent-7@gmail.com",
    "firstName": "parent",
    "lastName": "7",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "roleNames": ["PARENT_USER"]
}

### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/user
Content-Type: application/json

{
    "username": "parent-8",
    "password": "12345678aA@",
    "email": "parent-8@gmail.com",
    "firstName": "parent",
    "lastName": "8",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "roleNames": ["PARENT_USER"]
}


### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/user
Content-Type: application/json

{
    "username": "parent-9",
    "password": "12345678aA@",
    "email": "parent-9@gmail.com",
    "firstName": "parent",
    "lastName": "9",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "roleNames": ["PARENT_USER"]
}


### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/user
Content-Type: application/json

{
    "username": "parent-10",
    "password": "12345678aA@",
    "email": "parent-10@gmail.com",
    "firstName": "parent",
    "lastName": "10",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "roleNames": ["PARENT_USER"]
}

### REGISTER ACTION ###

# @name admin_register

POST {{rest}}/user
Content-Type: application/json

{
    "username": "admin",
    "password": "12345678aA@",
    "email": "chungnguyen10012000@gmail.com",
    "firstName": "admin",
    "lastName": "1",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "roleNames": ["ADMIN_USER"]
}

### REGISTER ACTION ###
# @name teacher_register

POST {{rest}}/user
Content-Type: application/json

{
    "username": "teacher-1",
    "password": "12345678aA@",
    "email": "thanhtrunga370qx@gmail.com",
    "firstName": "teacher",
    "lastName": "1",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "roleNames": ["TEACHER_USER"]
}

### REGISTER ACTION ###
# @name teacher_register

POST {{rest}}/user
Content-Type: application/json

{
    "username": "teacher-2",
    "password": "12345678aA@",
    "email": "teacher-2@gmail.com",
    "firstName": "teacher",
    "lastName": "2",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "roleNames": ["TEACHER_USER"]
}

### REGISTER ACTION ###
# @name teacher_register

POST {{rest}}/user
Content-Type: application/json

{
    "username": "teacher-3",
    "password": "12345678aA@",
    "email": "teacher-3@gmail.com",
    "firstName": "teacher",
    "lastName": "3",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "roleNames": ["TEACHER_USER"]
}

### REGISTER ACTION ###
# @name teacher_register

POST {{rest}}/user
Content-Type: application/json

{
    "username": "teacher-4",
    "password": "12345678aA@",
    "email": "teacher-4@gmail.com",
    "firstName": "teacher",
    "lastName": "4",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "roleNames": ["TEACHER_USER"]
}

### REGISTER ACTION ###
# @name teacher_register

POST {{rest}}/user
Content-Type: application/json

{
    "username": "teacher-11",
    "password": "12345678aA@",
    "email": "teacher-11@gmail.com",
    "firstName": "teacher",
    "lastName": "11",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "roleNames": ["TEACHER_USER"]
}


### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/user
Authorization: Bearer {{admin_access_token}}

### REGISTER ACTION ###
# @name teacher_register

POST {{rest}}/user/teacher
Content-Type: application/json

{
    "username": "chungnguyen",
    "email": "chung.nguyen10012001@hcmut.edu.vn",
    "firstName": "Nguyen",
    "lastName": "Chung",
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "roleNames": ["TEACHER_USER"]
}

### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}




###

# @name get_info_user
GET {{rest}}/user
Authorization: Bearer {{admin_access_token}}

###

# @name get_all_user
GET {{rest}}/user/teacher
Authorization: Bearer {{admin_access_token}}

###
# @name get_all_user
GET {{rest}}/user/student
Authorization: Bearer {{admin_access_token}}

###
# @name get_all_user
GET {{rest}}/user/parent
Authorization: Bearer {{admin_access_token}}

###

# @name refresh_token_admin
@admin_access_token_after = {{refresh_token_admin.response.body.accessToken}}
POST  {{rest}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "{{admin_refresh_token}}"
}



###

# @name get_all_user_after_refresh
GET {{rest}}/user
Authorization: Bearer {{admin_access_token_after}}

### STUDENT ACTION ###

# @name login_student
@student_access_token = {{login_student.response.body.accessToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "admin",
    "password": "12345678aA@"
}

###

# @name get_all_user_by_student
GET {{rest}}/user/teacher
Authorization: Bearer {{student_access_token}}


###

# @name get_all_user_by_student
GET {{rest}}/user/report/2022
Authorization: Bearer {{student_access_token}}


### 
# @name update_contest

PUT {{rest}}/user/change-password/1
Content-Type: application/json

{
    "pre_password": "12345678aA@",
    "new_password": "a8726357"
}





