@rest = {{$dotenv HOST}}/{{$dotenv API}}


### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-1_1",
    "password": "12345678aA@",
    "email": "student-1@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [5],
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-1_2",
    "password": "12345678aA@",
    "email": "student-1_2@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [5],
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-2_1",
    "password": "12345678aA@",
    "email": "student-2_1@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [6],
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-2_2",
    "password": "12345678aA@",
    "email": "student-2_2@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [6],
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-3_1",
    "password": "12345678aA@",
    "email": "student-3_1@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [7],
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-3_2",
    "password": "12345678aA@",
    "email": "student-3_2@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [7],
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-10",
    "password": "12345678aA@",
    "email": "student-10@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [14],
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name student_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "student-2",
    "password": "12345678aA@",
    "email": "student-2@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [5],
    "roleNames": ["STUDENT_USER"]
}

### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "parent-1",
    "password": "12345678aA@",
    "email": "parent-1@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [],
    "roleNames": ["PARENT_USER"]
}

### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "parent-2",
    "password": "12345678aA@",
    "email": "parent-2@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [],
    "roleNames": ["PARENT_USER"]
}

### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "parent-3",
    "password": "12345678aA@",
    "email": "parent-3@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [],
    "roleNames": ["PARENT_USER"]
}

### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "parent-4",
    "password": "12345678aA@",
    "email": "parent-4@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [],
    "roleNames": ["PARENT_USER"]
}

### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "parent-5",
    "password": "12345678aA@",
    "email": "parent-5@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [],
    "roleNames": ["PARENT_USER"]
}


### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "parent-6",
    "password": "12345678aA@",
    "email": "parent-6@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [],
    "roleNames": ["PARENT_USER"]
}


### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "parent-7",
    "password": "12345678aA@",
    "email": "parent-7@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [],
    "roleNames": ["PARENT_USER"]
}

### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "parent-8",
    "password": "12345678aA@",
    "email": "parent-8@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [],
    "roleNames": ["PARENT_USER"]
}


### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "parent-9",
    "password": "12345678aA@",
    "email": "parent-9@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [],
    "roleNames": ["PARENT_USER"]
}


### REGISTER ACTION ###

# @name parent_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "parent-10",
    "password": "12345678aA@",
    "email": "parent-10@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [],
    "roleNames": ["PARENT_USER"]
}

### REGISTER ACTION ###

# @name admin_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "admin",
    "password": "12345678aA@",
    "email": "admin@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [],
    "roleNames": ["ADMIN_USER"]
}

### REGISTER ACTION ###
# @name teacher_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "teacher-1",
    "password": "12345678aA@",
    "email": "teacher-1@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [],
    "roleNames": ["TEACHER_USER"]
}

### REGISTER ACTION ###
# @name teacher_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "teacher-2",
    "password": "12345678aA@",
    "email": "teacher-2@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [],
    "roleNames": ["TEACHER_USER"]
}

### REGISTER ACTION ###
# @name teacher_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "teacher-3",
    "password": "12345678aA@",
    "email": "teacher-3@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [],
    "roleNames": ["TEACHER_USER"]
}

### REGISTER ACTION ###
# @name teacher_register

POST {{rest}}/registration
Content-Type: application/json

{
    "username": "teacher-4",
    "password": "12345678aA@",
    "email": "teacher-4@gmail.com",
    "firstName": null,
    "lastName": null,
    "dateOfBirth": null,
    "profile_image_url": null,
    "sex": null,
    "phone": null,
    "address": null,
    "parent_ids": [],
    "roleNames": ["TEACHER_USER"]
}

### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "teacher-1",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/teacher-register-level/teacher/28
Authorization: Bearer {{admin_access_token}}

### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/teacher-register-level
Authorization: Bearer {{admin_access_token}}

### CREATE ART TYPE ACTION ###
# @name create_art_type

POST {{rest}}/teacher-register-level
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "teacher_id": 28,
    "course_id": 1,
    "degree_photo_url": "https://res.cloudinary.com/djtmwajiu/image/upload/v1656344895/tranh-bao-ve-moi-truong-01_gpsyin.png",
    "status": "Approved"
}

### CREATE ART TYPE ACTION ###
# @name create_art_type

POST {{rest}}/teacher-register-level
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "teacher_id": 3,
    "course_id": 1,
    "degree_photo_url": "https://res.cloudinary.com/djtmwajiu/image/upload/v1656344895/tranh-bao-ve-moi-truong-01_gpsyin.png",
    "status": "Approved"
}

### CREATE ART TYPE ACTION ###
# @name create_art_type

POST {{rest}}/teacher-register-level
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "teacher_id": 4,
    "course_id": 1,
    "degree_photo_url": "https://res.cloudinary.com/djtmwajiu/image/upload/v1656344895/tranh-bao-ve-moi-truong-01_gpsyin.png",
    "status": "Approved"
}

### GET ART TYPE ACTION ###
# @name get_all_art_type

POST {{rest}}/semester/calender/1
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "time": ["2022-08-08", "2022-08-10", "2022-08-12"]
}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/semester/schedule-class/1
Authorization: Bearer {{admin_access_token}}

### CREATE CONTEST ACTION ###
# @name get_info_user
GET {{rest}}/classes/info/3
Authorization: Bearer {{admin_access_token}}

### GET classes ACTION ###
# @name get_classes

GET  {{rest}}/classes/info

### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

POST {{rest}}/teacher-teach-semester
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "teacher_id": 4,
    "semester_course_id": 1
}


### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

POST {{rest}}/user-register-join-semester
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "student_id": 27,
    "semester_course_id": 1,
    "payer_id": 27,
    "price": 2000000
}


### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

POST {{rest}}/teacher-teach-semester
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "teacher_id": 2,
    "semester_course_id": 1
}

### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester
POST {{rest}}/classes
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "name": "Lớp CM-1",
    "creator_id": 1,
    "registration_id": 1,
    "security_code": "CM-1HK2022",
    "user_register_join_semester": [1,2,3,4,5,6]

}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST {{rest}}/schedule
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "name": "Lịch học 1",
    "creator_id": 1
}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST {{rest}}/schedule-item
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "schedule_id": 1,
    "lesson_time": 1,
    "date_of_week": 2
}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST {{rest}}/schedule-item
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "schedule_id": 1,
    "lesson_time": 2,
    "date_of_week": 4
}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST {{rest}}/schedule-item
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "schedule_id": 1,
    "lesson_time": 1,
    "date_of_week": 6
}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST {{rest}}/lesson-time
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "start_time": "07:00:00",
    "end_time": "08:00:00"
}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST {{rest}}/lesson-time
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "start_time": "10:00:00",
    "end_time": "11:00:00"
}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/semester
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "name": "Học kì 1 năm học 2022",
    "description": "",
    "number": 1,
    "start_time": "2022-08-12T12:59:11.332",
    "year": 2022,
    "creator_id": 1
}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST {{rest}}/semester-course
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "creation_id": 1,
    "course_id": 1,
    "schedule_id": 1

}

### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

POST {{rest}}/teacher-leave
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "section_id": 1,
    "teacher_id": 4,
    "class_id": 1,
    "substitute_teacher_id": 5,
    "description": ""
}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/section-template
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "creator_id": 1,
    "course_id": 1,
    "name": "Giao an 10",
    "description": "",
    "number": 10,
    "teaching_form": true
}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/contest
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "name": "Cuộc thi vẽ tranh gia đình",
    "description": "Vẽ về những người thân trong gia đình",
    "max_participant": 20,
    "registration_time": "2022-07-12T12:59:11.332",
    "image_url": "https://res.cloudinary.com/djtmwajiu/image/upload/v1656344895/tranh-bao-ve-moi-truong-01_gpsyin.png",
    "start_time": "2022-08-12T12:59:11.332",
    "end_time": "2022-09-12T12:59:11.332",
    "is_enabled": true,
    "creater_id": 1,
    "art_age_id": 1,
    "art_type_id": 1
}

### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/semester-course?page=0&size=10


### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/classes/teacher/2



### GET ART TYPE ACTION ###
# @name get_all_art_type

GET {{rest}}/course/teacher/2



### CREATE COURSE ACTION ###
# @name create_course

### CREATE ART AGE ACTION ###
# @name create_art_age

POST {{rest}}/art-age
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "name": "4-6 tuổi",
    "description": "Độ tuổi từ 4-6 tuổi"
}

### CREATE ART AGE ACTION ###
# @name create_art_age

POST {{rest}}/art-age
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "name": "5-10 tuổi",
    "description": "Độ tuổi từ 5-10 tuổi"
}


### CREATE ART AGE ACTION ###
# @name create_art_age

POST {{rest}}/art-level
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "name": "Cơ bản",
    "description": "Dành cho bạn mới bắt đầu"
}

### CREATE ART AGE ACTION ###
# @name create_art_age

POST {{rest}}/art-level
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "name": "Nâng cao",
    "description": "Dành cho bạn mới bắt đầu"
}

### CREATE ART TYPE ACTION ###
# @name create_art_type

POST {{rest}}/art-type
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "name": "Sơn dầu",
    "description": "Thể loại sơn dầu"
}

### CREATE ART TYPE ACTION ###
# @name create_art_type

POST {{rest}}/art-type
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "name": "Chì màu",
    "description": "Thể loại chì màu"
}

### CREATE ART TYPE ACTION ###
# @name create_art_type

POST {{rest}}/course
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "name": "Khóa học mầm chì màu cơ bản",
    "description": "<p>hello nguyen van chung</p>",
    "max_participant": 20,
    "num_of_section": 10,
    "price": 2000000,
    "image_url": "https://res.cloudinary.com/djtmwajiu/image/upload/v1656344893/lop-day-hoc-ve-tre-em-be-thieu-nhi-370x255_natvks.png",
    "is_enabled": false,
    "creator_id": 1,
    "art_age_id": 1,
    "art_type_id": 1,
    "art_level_id": 1
}

### CREATE LESSON TIME ACTION ###
# @name create_lesson_time

POST {{rest}}/schedule
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "name": "Lịch học 1",
    "creator_id": 1
}

###

# @name get_info_user
GET {{rest}}/user/1
Authorization: Bearer {{admin_access_token}}

###

# @name get_all_user
GET {{rest}}/user/teacher
Authorization: Bearer {{admin_access_token}}

###
# @name get_all_user
GET {{rest}}/user/student
Authorization: Bearer {{admin_access_token}}

###
# @name get_all_user
GET {{rest}}/user/parent
Authorization: Bearer {{admin_access_token}}

###

# @name refresh_token_admin
@admin_access_token_after = {{refresh_token_admin.response.body.accessToken}}
POST  {{rest}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "{{admin_refresh_token}}"
}

###

# @name get_all_user_after_refresh
GET {{rest}}/user
Authorization: Bearer {{admin_access_token_after}}

### STUDENT ACTION ###

# @name login_student
@student_access_token = {{login_student.response.body.accessToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "student",
    "password": "12345678aA@"
}

###

# @name get_all_user_by_student
GET {{rest}}/user
Authorization: Bearer {{student_access_token}}





