### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "student-1_1",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/user-grade-exercise-submission
Content-Type: application/json

{
    "student_id": 1,
    "exercise_submission_id": 1,
    "feedback": "",
    "score": 1
}

### CREATE CONTEST ACTION ###
# @name create_contest

POST {{rest}}/user-grade-exercise-submission
Content-Type: application/json

{
    "student_id": 1,
    "exercise_submission_id": 1,
    "feedback": "",
    "score": 1
}

### 
# @name update_contest

PUT {{rest}}/user-grade-exercise-submission/1/1
Content-Type: application/json

{
    "student_id": 1,
    "exercise_submission_id": 1,
    "feedback": "xx",
    "score": 10
}

### GET CONTEST ACTION ###
# @name get_contest

GET  {{rest}}/user-grade-exercise-submission