### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "student-1",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

POST {{rest}}/user-register-join-semester
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "student_id": 22,
    "semester_classes_id": 1,
    "payer_id": 12,
    "price": "1000"
}

### GET TEACHER GRADE semester ACTION ###
# @name get_teacher_grade_semester

GET {{rest}}/user-register-join-semester/16

### GET TEACHER GRADE semester ACTION ###
# @name get_teacher_grade_semester

GET {{rest}}/user-register-join-semester/payer-report/12

### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

GET {{rest}}/user-register-join-semester

### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

GET {{rest}}/user-register-join-semester/total-money

### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

GET {{rest}}/user-register-join-semester/payer/12


### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

GET {{rest}}/user-register-join-semester/report/2022


### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

POST {{rest}}/user-register-join-semester/payment?ids=1,2
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "partnerCode":"MOMOIOLD20190129",
    "orderId":"01234567890123451633504872421",
    "requestId":"01234567890123451633504872421",
    "amount":1000,"orderInfo":"Test Thue 1234556",
    "orderType":"momo_wallet","transId":2588659987,
    "resultCode":0,"message":"Giao dịch thành công.",
    "payType":"qr","responseTime":1633504902954,
    "extraData":"eyJyZXN1bHRfbmFtZXNwYWNlIjoidW1hcmtldCIsImVycm9yIjoiIiwic3RhdGUiOjZ9",
    "signature":"90482b3881bdf863d5f61ace078921bbc6dbb58b2fded35261c71c9af3b1ce4f"
}