### ADMIN ACTION ###

# @name login_admin
@admin_access_token = {{login_admin.response.body.accessToken}}
@admin_refresh_token = {{login_admin.response.body.refreshToken}}
POST {{rest}}/auth
Content-Type: application/json

{
    "username": "student-1_1",
    "password": "12345678aA@"
}

@rest = {{$dotenv HOST}}/{{$dotenv API}}

### CREATE STUDENT REGISTER JOIN semester ACTION ###
# @name create_student_register_join_semester

POST {{rest}}/user-register-join-semester
Authorization: Bearer {{admin_access_token}}
Content-Type: application/json

{
    "student_id": 23,
    "semester_class_id": 2,
    "payer_id": 7,
    "price": 2000000
}

### GET TEACHER GRADE semester ACTION ###
# @name get_teacher_grade_semester

GET {{rest}}/user-register-join-semester/16

### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

GET {{rest}}/user-register-join-semester


### GET USER GRADE semester ACTION ###
# @name get_all_user_grade_semester

GET {{rest}}/user-register-join-semester/report/2022